const stories = {
  1: {
    title: "蒼天のイシュガルドにて",
    description: "DECEMBER 02, 2025",
    image: "images/story_card/story1.jpg",
    gallery: [
      "images/gallary/story1/gallery1.jpg",
      "images/gallary/story1/gallery2.jpg",
      "images/gallary/story1/gallery3.jpg",
      "images/gallary/story1/gallery4.jpg",
    ],
    chats: [
      {
        type: "subtitle",
        text: "竜詩戦争集結",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "これで",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "今度こそオルシュファンも、イゼルも",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ふたりは、ちゃんと、うつくしい星の海を巡って",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "また会えるといいなと、思いました",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "僕らの命は世界をめぐってる",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: " 旅を続けていたら、またきっと、会えるよ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "はい",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "思い出しました 冒険者になろうって思ったときのこと",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "かっこいい冒険者の・・・そういえば・・・その人も、ヴィエラのひとだったなあ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "助けてもらったんです。危ないところを",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "かっこいい、って思って。冒険者を目指したんです。",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "そんなことがあったんだ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "はい！",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "そのあと、師匠にあって",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠みたいに、もっと強くなりたいっておもって",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "わたしがいま願っているのは、かっこよくて強い冒険者になること",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "つぎにまたオルシュファンにあったら、イイ！っていってもらえる冒険者でありたいなって",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "おもいました",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "凄く...イイね",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "彼の言葉を借りてしまった",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ふふ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: " 似てる！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "きっとその冒険者の人もオルシュファンも、いつか成長した君に出会って旅の話を聞いたら",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: " ふふ",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "きっと喜ぶと思うよ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "はい！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "すごいなあ、君は",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "十分かっこいいよ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ほんとですか！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "もちろん",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "へへ",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "成長を見るのが楽しみだ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "1番近くで見ててください！",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠にね かわいいって言ってもらえるのも思ってもらえるのもすごくすき",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "それも、もちろん",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "かっこいいなって思ってもらえるのもすごくうれしいです",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "（何も言わずに嬉しそうに微笑む）",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "（ほら、いっておいで",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "君を待ってる人がいる",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "はい！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "Colune LuneはRudy Forsythをなでた。",
      },
      {
        type: "subtitle",
        text: "あなたにだけこぼせる話",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ししょう！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "どうしたの？",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "一個だけ誰にもいえなかったことがあって",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: " きいてもらえないでしょうか",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "いいよ",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "教えて",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "あのね",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "Rudy ForsythはColune Luneに相槌を打った",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "でもやっぱり、みんなで青空の下に集まったとき",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "そこに、オルシュファンとイゼルもいてほしかった",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "なあって",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "おもっちゃって",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "・・・",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "そうだね",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "本当にそうであれたらと",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "今でも思ってしまうよ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠も？",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "うん",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "こういうきもちは",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ずっと持っててもいいのかなあって",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "頑張って、そう思わないほうがいいのかなあって",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "思ったりして",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "きっと僕たちは",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "亡くした人を置いて行って、これからも歩み続ける宿命にあるかもしれない",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "けれど、足が止まってしまいそうな時に",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "君の背を押すのは、君が亡くしたくなかった人たちなんだと思う",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "だから忘れないで",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "覚えていてあげて",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "・・・師匠もそうだった？",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "幾度も喪失を味わって",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "分からなくなってしまった時もあったけど",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "最後はそうだった",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "失くしたくなかった人たち、失くしたくない人たちが背を押してくれた",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "・・・うん",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "そっかあ うん そうだ",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "本当はそんなの御免だったんだけどね、どうしても彼らの事を思うと歩みを止められないんだ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "うん",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠は、いろんなものを見て、聞いて、感じて、考えて、歩いて、そのさきできっと、その旅がよかったって思える時がきたんですよね",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "そうだね",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "・・・（じ、と師匠を見る）",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "Rudy ForsythはColune Luneに疑問を抱いてみせた。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "コルネは、師匠が歩いてきた旅路に比べたら、まだまだ短い道のりの途中で",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠が見たり聞いたり感じてきたものに比べたら、まだまだ全然だけど",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "いつか、師匠のいる場所にたどり着くから",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "そこで、コルネをいっぱい撫でてくれた10倍くらい撫でてあげますから！",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "待っててください",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "撫でてくれるの？",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ぎゅーもします！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "君がご褒美をいっぱいもらうのじゃなくて？",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "ふふ、おもしろいね",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠をいっぱい撫でて抱きしめさせてもらえることが、コルネにとってのご褒美です！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "どうして君がそう思うのか、今の僕には不思議でならないけれど",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: " いつか分かる日が来るのかな",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "オトメゴコロってやつですね",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "あっ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "でも",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "待ってください",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "うそいいました",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "ん？",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "Colune Luneは考えた。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "撫でてぎゅーもして",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ちゅうもいっぱいさせてください！",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "Colune LuneはRudy Forsythにおねだりした。",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "ふふ、いいよ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "Colune LuneはRudy Forsythにすごく喜んでみせた。",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "それがご褒美になるなら",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "やったーーー！",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "やくそくですよ！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "うん",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "Colune LuneはRudy Forsythを笑った。",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "Rudy Forsythは愛おしそうにColune Luneを撫でた",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "お話きいてくれてありがとうございましたししょう",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しは参考になったかな？",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "はい！！！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "それはよかった",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "またがんばれます！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "また、冒険を続けていこうね",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "・・・はい！",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "Colune LuneはRudy Forsythに喜んでみせた。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "そのためにもしっかり休息をとりましょう(`･ω･´)",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "そうだね",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "Colune LuneはRudy Forsythをなでた。",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "休息の提案をされるなんて",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "すっかり君も立派な冒険者だ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ふふん",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "と、言いたいところですが・・・",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "うん？",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ししょう、やっぱり　オトメゴコロは　アリゼーにきいておいてください",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ヤ・シュトラもおしえてくれるとおもいます",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "えっ...............",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "頑張って...みる......",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ふふ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "Colune LuneはRudy Forsythをなでた。",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "Rudy Forsyth困ったようにColune Luneに笑いかける",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "さっきの休息をとりましょう、はですね",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "うん",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠におふとんまで連れて行ってもらって、ぎゅってしてもらいたい",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "って意味です",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "えっ",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "あっ....",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "Rudy ForsythはColune Luneに慌ててみせた。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "Colune Luneは笑った。",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "ごめんね...",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "Rudy ForsythはColune Luneを歓迎した。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "Colune LuneはRudy Forsythにすごく喜んでみせた。",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "さ、おいで",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "わーい！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "Rudy ForsythはColune Luneを歓迎した。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "（ししょうにくっつく！）",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "（手招きを軽くして、くっつきに来たらゆるく抱きしめ）",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "へへ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "おやすみなさい（すりりと頭をくっつける）",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "おやすみ",
      },
    ],
  },

  2: {
    title: "星座と灯を辿って",
    description: "DECEMBER 08, 2025",
    image: "images/story_card/story2.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "今日はなんだか",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "はい",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "色んな事に思いをはせてしまう日だったね",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "・・・はい・・・",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "君はさ、役割って役目ってなんだと思う？",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "生まれ死んで、そうしてやっと答えを得る事であるはずなのに",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "何をもってして人はそれを役目と言うのだろうね",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ちょうど",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "コルネも、役目とか役割ってなんだろう って、ぼんやり考えてました",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "そっか",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "じゃあ一緒だったんだ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "はい！！",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "・・・でも、なんだろうって思うばかりで",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "エスティニアンやミンフィリアが果たそうとする姿を見ながら",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "いろいろ・・・こう・・・（もごもごとする）",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "難しいね",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "難しかった、です",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠はこれまでに、考えたことはありますか",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "質問に質問でかえしちゃうんですが・・・",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "ふふ、大丈夫だよ",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "......最後まで僕にはわからなかったよ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "・・・（じ、と師匠を見る）",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠にとっても、難題なんですね",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "そうだねえ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "コルネがおもったのは",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "あ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "コルネが何言ってもきらいにならないでくれますか",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "嫌いに...？",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "それは勿論、大丈夫だよ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "へへ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "（←大丈夫といわれるだろうと思いながら言った顔）",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "（可愛い♡）",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ちょっとだけ、いいなあと…うーん。多分、うらやましく思いました",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "役目が見つかった人たちが？",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "はい",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "どうしてか、教えてくれる",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "コルネは、旅が楽しいなあとか、空が綺麗だなあとか、日々をいきることとか、目の前のことにいっぱいいっぱいで",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "こう…おいていかれているような、そんな感覚がちょっとあったりして",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "命の使い方を決めて歩んでいるひとが、すごく・・・まぶしく感じました",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "うん、よくわかるよ",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: " 今回の旅は、アルフィノもアリゼーも二人とも自分がどこへ向かいたいか、役目のようなものを見つけていたね",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "うん",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "ミンフィリアもそうだけど、僕もすごくまぶしいなって思った",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "でも、そうだな",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "僕も、君と同じように世界を見て、人と出会ってそれで十分だったけれど",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "君とこうして話しながら、旅路を振り返って思いだしたことがある",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "思い出したこと！",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "どういうことですか？",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "大事な人がいた、心を通わせた人もいた、それは対立でかもしれないし道を同じくしてかもしれない",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "そういう人たちのね、気持ちや、思いや、大事にしたいものを。彼らが見ていた世界を",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "無かったことになんてしたくなかったんだなって",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: " 君と会話をして思いだした",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "役目とかの話じゃないんだけどね",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "Rudy Forsyth困ったようにColune Luneに笑いかける",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "どういうことですか？",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠にとって大事なことを思い出せた、ってことですか？",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "うん、そうだね　君の言うとおりだ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "へへ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "だったら、うれしいです",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "ふふ　ありがとう",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "絶望の渦中にあろうとも、きっとこれがあれば歩いていける",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "僕にとっては君に話したことがそうなのかもしれないね",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "だから、そうだな...",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "役目がわからなくても、導があればいいんじゃないかな",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "ほら、旅には星のような道しるべがひつようでしょ？",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "たしかに・・・！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "僕たちは、英雄や光の戦士である前に、冒険者であり旅人だ",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "君が自分の中の星を見つけたなら、それが輝き続ける限り",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "きっと迷う事はない",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "っていうのは....どうかな....？",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "いまとても",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "胸の中があついです",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "ふふ、よかった",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "いつか見つかるといいね",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "それかもう見つけているのかな",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "Colune Luneは考えた。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "いろんな気持ちがあって",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "どれもが星に見えるような、そうではないような、そんな感じです",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "想いに応えたいな、とか。使命のために頑張る人を応援したいな、とか、いろいろあるし",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "でも・・・たまに、こうして師匠とごはんたべてごろん！ってする日が毎日続いたらな～って思うときもあるし",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "そういう日々を迎えられるようにがんばろう、って思ったりもするし",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "でも、やっぱり、かっこいい冒険者になりたい！って思うのはずっとかわらなくて",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "どこかで、そういうちっちゃい星のどれかが、ものすごく光るのかな",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠の言葉をきいて、そう想いました",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "そっか",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "君の中では色んなものがきらきら輝いているんだね",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "それはとっても素敵なことだ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠は、導に気づいたのはどういうとき？",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "旅の途中で、ふと気がついた？",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "どうだったかな...",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "う～ん",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "それはまだ少し",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "秘密かな",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "あ！ひみつだ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "みすてりあすだ",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "Rudy ForsythはColune Luneに静寂を促してみせた。",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "ふふ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "Colune Luneは笑った。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "コルネ、師匠のこと、ぜんぜんしらないんだなあ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "みらいで教えてくれる？",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "もちろん",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "これからもたくさん話をしよう",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "します！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "それで、僕の事も知ってほしいし、君の事もたくさん知りたいな",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "はい！ コルネのお話をきいてくれるのもうれしいし",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠のお話をしてもらえるのもとっても嬉しいです",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "きょう",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "もし師匠がいなかったらコルネはいろいろ考え込んじゃって眠れなかったので",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "「今日の師匠の役目」はコルネの安眠を守ることだったのかもしれませんね！",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "Colune Luneは笑った。",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "Rudy ForsythはColune Luneを笑った。",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "それは",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "この上ない大きな役目だったね",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "おつとめごくろう（黒渦団のなんかごついひとの真似）",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "はい、ありがとうございます（真似を見て目を細めながら）",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "ふふふ",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "今ふとおもったんですけど",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "うん？",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "師匠がコルネの成長を見ることを楽しみ？にしてくれてたり、一緒の旅を嬉しく思ってくれてるので",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "コルネも、全力で楽しもう！いっぱい頑張ろう！て思えてるところがたくさんあるので",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "今、導にさせてもらっているものは師匠にもらってるかもです！",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "....それは驚いた...",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "僕が、君にそこまで？",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "そりゃあもちろん",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "です！",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "本当はちゃんと、自分で、考えたり見つけていくべきものなんだろうなっていうのもわかってます",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "でも、この導はコルネにとって、とても大事なものなので、ずっと持っててもいいですか？",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "君に、そういわれると",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "この世界で初めて錨を落とせたようなそんな気分になって",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "すごくうれしいよ",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "ありがとう",
      },
    ],
  },

  3: {
    title: "きみでいっぱいになりたい",
    description: "DECEMBER 17, 2025",
    image: "images/story_card/story3.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        type: "subtitle",
        text: "竜詩戦争集結",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "まだ眠くないの？",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "君が起きてるから。",
      },
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  4: {
    title: "ししょうのばか",
    description: "JANUARY 29, 2026",
    image: "images/story_card/story4.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  5: {
    title: "きみがひとり空をゆくから",
    description: "FEBRUARY 25, 2026",
    image: "images/story_card/story5.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  6: {
    title: "結局きみのことを、考えてる",
    description: "FEBRUARY ??, 2026",
    image: "images/story_card/story6.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  7: {
    title: "きみを愛でひたひたにしたい",
    description: "MARCH 02, 2026",
    image: "images/story_card/story7.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  8: {
    title: "たからもののじかん",
    description: "MARCH 03, 2026",
    image: "images/story_card/story8.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  9: {
    title: "さそってんのよ",
    description: "MARCH 05, 2026",
    image: "images/story_card/story9.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  10: {
    title: "お待たせ、待った？",
    description: "MARCH 05, 2026",
    image: "images/story_card/story10.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  11: {
    title: "だ～れだ！",
    description: "MARCH ??, 2026",
    image: "images/story_card/story11.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  12: {
    title: "くっつきむしのまほう",
    description: "MARCH ??, 2026",
    image: "images/story_card/story12.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  13: {
    title: "ゆうわくしっぱい",
    description: "MARCH ??, 2026",
    image: "images/story_card/story13.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  14: {
    title: "おくちは今からお預けです",
    description: "MARCH ??, 2026",
    image: "images/story_card/story14.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  15: {
    title: "₍ᐡ•̥~•̥ᐡ₎",
    description: "MARCH ??, 2026",
    image: "images/story_card/story15.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  16: {
    title: "かわいいキミに甘やかされたい",
    description: "MARCH ??, 2026",
    image: "images/story_card/story16.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
  17: {
    title: "さわりあいっこ、こるねの番",
    description: "APRIL 13, 2026",
    image: "images/story_card/story17.jpg",
    gallery: [
      "images/gallary/story2/gallery1.png",
      "images/gallary/story2/gallery2.png",
      "images/gallary/story2/gallery3.png",
    ],
    chats: [
      {
        character: "rudy",
        name: "RUDY",
        icon: "images/rudy.png",
        text: "少しだけ休もう。",
      },
      {
        character: "colune",
        name: "COLUNE",
        icon: "images/colune.png",
        text: "じゃあ、隣にいてもいい？",
      },
    ],
  },
};
